[project]
name = "investmentagents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "strands-agents-tools[a2a-client]>=0.2.8",
    "strands-agents[a2a,ollama,otel]>=1.9.1",
    "mem0ai>=0.1.117",
    "chromadb>=1.1.0",
]

[tool.uv.workspace]
members = [
    "mcp-servers/asset-data-server",
    "mcp-servers/simfin-fundamentals-data-server",
    "mcp-servers/finnhub-fundamentals-data-server",
    "mcp-servers/finnhub-news-data-server",
    "mcp-servers/reddit-news-data-server",
    "mcp-servers/google-news-data-server",
    "mcp-servers/duckduckgo-news-data-server",
    "mcp-servers/yfin-market-data-server",
    "mcp-servers/stockstats-market-data-server",
    "mcp-servers/mem0-server",
]

[dependency-groups]
dev = [
    "arize-phoenix>=11.21.0",
    "pre-commit>=4.2.0",
    "pytest>=8.4.2",
    "trio>=0.31.0",
]

[tool.pytest.ini_options]
anyio_backends = ["asyncio"]
